POST http://localhost:8000/api/caixa/3/movimentacao HTTP/1.1
content-type: application/json
Authorization: Bearer 29|0WAZYsAPuYtgKOtC0Xqqv6VQ57YrPBzh0NEAGdy853ceb6c3

{
    "type": "entrada",
    "value": 1500.75,
    "description": "Pagamento recebido pelo serviço prestado",
    "payment_method": "pix",
    "additional_data": []
}