services:
  # Servidor Nginx como proxy reverso
  nginx:
    image: nginx:1.25.1-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/production.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www:/var/www/certbot # webroot para certbot
      - ./certbot/conf:/etc/letsencrypt # certificados e configs do certbot
      - ./backend/public:/var/www/html/public
      - ./data/logs/nginx:/var/log/nginx
    depends_on:
      - frontend
      - backend
    networks:
      - alfa
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot --quiet; sleep 12h & wait $${!}; done;'"
    depends_on:
      - nginx
    networks:
      - alfa
    restart: unless-stopped
  # Frontend Next.js
  frontend:
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_ACCESS_URL: ${NEXT_PUBLIC_ACCESS_URL}
        NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: ${NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME}
        NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET: ${NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET}
        NEXT_PUBLIC_CLOUDINARY_HIDE_SESSION: ${NEXT_PUBLIC_CLOUDINARY_HIDE_SESSION}
    container_name: frontend
    volumes:
      - ./frontend/public:/app/public
    environment:
      - NODE_ENV=production
    networks:
      - alfa
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G

  # Backend Laravel
  backend:
    ports:
      - "9000:9000"
    build:
      context: .
      dockerfile: backend/Dockerfile
      args:
        APP_UID: ${APP_UID:-1000}
        APP_USER: ${APP_USER:-laravel}
        APP_HOME: ${APP_HOME:-/home/laravel}
    container_name: backend
    volumes:
      - ./data/uploads:/var/www/html/storage/app/public
      - ./backend/storage/logs:/var/www/html/storage/logs
    environment:
      - APP_ENV=${APP_ENV}
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=${APP_DEBUG}
      - APP_URL=${APP_URL}
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=pdvalfa360
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_BLACKLIST_ENABLED=${JWT_BLACKLIST_ENABLED}
      - CACHE_STORE=redis
      - SESSION_DRIVER=redis
      - QUEUE_CONNECTION=redis
      - REDIS_HOST=redis
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=6379
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - alfa
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:9000/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 4G
        reservations:
          cpus: "0.5"
          memory: 512M
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
      - /var/tmp
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID

  # Banco de Dados MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=pdvalfa360
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - alfa
    restart: always
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${MYSQL_ROOT_PASSWORD}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: 6G

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD} --bind 0.0.0.0 --protected-mode yes
    ports:
      - "127.0.0.1:6379:6379" # Só localhost, não exposto externamente
    volumes:
      - ./data/redis:/data
    networks:
      - alfa
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

networks:
  alfa:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: alfa_network
    ipam:
      config:
        - subnet: 172.18.0.0/16
