name: Deploy to Production

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Production
        run: |
          ssh -o StrictHostKeyChecking=no deploy@161.97.93.119 "cd /srv/alfa360 && \
          git pull origin main && \
          docker-compose down && \
          docker-compose build && \
          docker-compose up -d && \
          docker-compose exec backend php artisan migrate --force && \
          docker-compose exec backend php artisan config:cache && \
          docker-compose exec backend php artisan route:cache && \
          docker-compose exec backend php artisan view:cache"
