name: Deploy to Production

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy backend and frontend with rollback
        run: |
          ssh deploy@161.97.93.119 "
            set -e  # Para o deploy se algum comando falhar
            cd /srv/alfa360
            git fetch origin main
            git reset --hard origin/main
            TIMESTAMP=$(date +'%Y%m%d%H%M%S')
            
            # --- Backend ---
            if git diff --name-only HEAD~1 HEAD | grep '^backend/'; then
              echo 'Backend changed, creating backup image...'
              docker tag alfa360_backend:latest alfa360_backend:backup-$TIMESTAMP
              
              echo 'Building and deploying backend...'
              docker-compose build backend
              docker-compose up -d backend

              # Check container status
              if ! docker ps --filter 'name=backend' --filter 'status=running' | grep backend; then
                echo 'Backend failed to start, rolling back...'
                docker tag alfa360_backend:backup-$TIMESTAMP alfa360_backend:latest
                docker-compose up -d backend
                exit 1
              fi

              echo 'Running migrations and caching...'
              docker-compose exec backend php artisan migrate --force
              docker-compose exec backend php artisan config:cache
              docker-compose exec backend php artisan route:cache
              docker-compose exec backend php artisan view:cache
            else
              echo 'No backend changes, skipping backend deploy.'
            fi

            # --- Frontend ---
            if git diff --name-only HEAD~1 HEAD | grep '^frontend/'; then
              echo 'Frontend changed, creating backup image...'
              docker tag alfa360_frontend:latest alfa360_frontend:backup-$TIMESTAMP

              echo 'Building and deploying frontend...'
              docker-compose build frontend
              docker-compose up -d frontend

              # Check container status
              if ! docker ps --filter 'name=frontend' --filter 'status=running' | grep frontend; then
                echo 'Frontend failed to start, rolling back...'
                docker tag alfa360_frontend:backup-$TIMESTAMP alfa360_frontend:latest
                docker-compose up -d frontend
                exit 1
              fi
            else
              echo 'No frontend changes, skipping frontend deploy.'
            fi

            # --- Tag release ---
            git tag -a deploy-$TIMESTAMP -m 'Deploy $TIMESTAMP'
            git push origin deploy-$TIMESTAMP
          "
