name: Deploy to Production

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy backend and frontend with rollback and MySQL backup
        run: |
          ssh -o StrictHostKeyChecking=no deploy@161.97.93.119 "
            set -e  # Para o deploy se algum comando falhar
            cd /srv/alfa360

            echo '--- Fetching latest code ---'
            git fetch origin main
            git reset --hard origin/main

            TIMESTAMP=\$(date +'%Y%m%d%H%M%S')

            # --- Backup MySQL ---
            echo '--- Creating MySQL backup ---'
            mkdir -p /srv/backups
            docker exec mysql \
              mysqldump -u root -p'${{ secrets.MYSQL_ROOT_PASSWORD }}' pdvalfa360 > /srv/backups/mysql-backup-\$TIMESTAMP.sql
            echo 'MySQL backup created: /srv/backups/mysql-backup-'"\$TIMESTAMP.sql"

            # --- Backend Deploy ---
            if git diff --name-only HEAD~1 HEAD | grep '^backend/'; then
              echo '--- Backend changes detected ---'
              docker tag alfa360_backend:latest alfa360_backend:backup-\$TIMESTAMP

              docker-compose build backend
              docker-compose up -d backend

              echo '--- Checking backend health ---'
              if ! docker ps --filter 'name=backend' --filter 'status=running' | grep backend; then
                echo 'Backend failed to start! Rolling back...'
                docker tag alfa360_backend:backup-\$TIMESTAMP alfa360_backend:latest
                docker-compose up -d backend
                exit 1
              fi

              echo '--- Running Laravel optimizations ---'
              docker-compose exec backend php artisan migrate --force
              docker-compose exec backend php artisan config:cache
              docker-compose exec backend php artisan route:cache
              docker-compose exec backend php artisan view:cache
            else
              echo 'No backend changes detected.'
            fi

            # --- Frontend Deploy ---
            if git diff --name-only HEAD~1 HEAD | grep '^frontend/'; then
              echo '--- Frontend changes detected ---'
              docker tag alfa360_frontend:latest alfa360_frontend:backup-\$TIMESTAMP

              docker-compose build frontend
              docker-compose up -d frontend

              echo '--- Checking frontend health ---'
              if ! docker ps --filter 'name=frontend' --filter 'status=running' | grep frontend; then
                echo 'Frontend failed to start! Rolling back...'
                docker tag alfa360_frontend:backup-\$TIMESTAMP alfa360_frontend:latest
                docker-compose up -d frontend
                exit 1
              fi
            else
              echo 'No frontend changes detected.'
            fi

            # --- Tag release ---
            echo '--- Tagging release ---'
            git tag -a deploy-\$TIMESTAMP -m 'Deploy \$TIMESTAMP'
            git push origin deploy-\$TIMESTAMP

            echo '--- Deploy completed successfully ---'
          "
